title: Wenjie You's Homepage
page-top-title: Wenjie You
top-section-bg-text: Artificial Intelligence
home-subtitle: Wenjie You&ensp;|&ensp;游文杰 
copyright-text: '&copy; Wenjie You 2023-2025. All Rights Reserved.'
